### ISSUE TITLE
Install from Melpa fails

### ISSUE THREAD

**Issue by lcacciari** [isamert/lab.el#12]
When trying to install the package using Melpa with the following `use-packege` invocation:

```
(use-package lab
  :config
  (setq lab-host "https://gitlab.com"))

```

I get the following `(error "Package ‘auth-source’ (version 23.1) is unavailabl...")`.

Locking at the package list, I see version     20241004.818 of lab marked as incompatible.

The output of `emacs-version` is the following:

> GNU Emacs 29.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.41, cairo version 1.18.0) of 2024-09-17, modified by Debian

**Comment by sebastiaanspeck** [comment]
I get the same error, I am using Emacs 30:
> GNU Emacs 30.0.92 (build 2, x86_64-w64-mingw32) of 2024-10-30

**Comment by isamert** [comment]
Hopefully it's fixed now (or in a day or so, when MELPA gets updated I guess?). Thanks for letting me know!
