### ISSUE TITLE
[FR] [RFC] Add pipeline Security findings feature

### ISSUE THREAD

**Issue by pataquets** [isamert/lab.el#7]
I'm using the package and it's awesome, thank you very much for sharing!

Unless you're on Ultimate tier, security findings (secret detection, etc.) in pipelines are not _prominently_ displayed on MRs [(docs)](https://docs.gitlab.com/ee/user/application_security/index.html#merge-request).
Having it in Lab would be great, but I don't even know how such a feature would be implemented UX-wise (a notification as done for finished pipelines might do?), but definitely this package might be a good fit for sure to gain visibility into such findings.

VSCode Gitlab extension has some support (not used myself):
https://marketplace.visualstudio.com/items?itemName=gitlab.gitlab-workflow#security-findings

Comments & feedback on how such a feature could possibly be done (and coded) would be much appreciated.

**Comment by isamert** [comment]
> I'm using the package and it's awesome, thank you very much for
> sharing!

Thanks, good to hear that it's useful to you!

> Having it in Lab would be great, but I don't even know how such a
> feature would be implemented UX-wise ...

I'm not quite familiar with the mentioned feature of GitLab (so please
correct me if I am missing something), this can be added as an action
to merge requests. So when a user acts on a merge request, they can
select the "security scan" action. After selecting this action,
possibly a buffer (maybe an org-mode buffer where each header is a
vulnerability and the body of the header contains the details?) can be
utilized for listing the vulnerabilities etc.

To add such action to merge requests, you can add this action to

```elisp
;; Find the following line and add this action as follows
(lab--define-actions-for merge-request
  ;; ... other actions ...
  (?s "Security Scanning"
      ;; Here we have the `it' object, representing the merge-request.

      ;; AFAIK, the security scan report is an artifact, so we can
      ;; download it using artifacts api
      ;; Not quite sure which job has this security report but we
      ;; should be able to get it through `it' object somehow.
      (let ((result (lab--request (format "projects/:id/jobs/:job_id/artifacts" .project_id GET-JOB-ID-SOMEHOW?))))
        ;; parse the result and put the result into a buffer?
        ;; ...
        )))
```

> ... (a notification as done for finished pipelines might do?) ...

Do you mean automatically opening the vulnerabilities right after
pipeline finishes? If so, maybe we can utilize the
`lab-watch-pipeline` function. Right now it only shows a notification
when pipeline finishes but I can extend it in a way that it runs an 
arbitrary function when pipeline finishes.

Hopefully this is helpful. Do not hesitate asking more questions if
it's not clear. I'll be very happy to help.

**Comment by isamert** [comment]
Going to close this issue for now. If you have an draft
implementation, you can open a PR and we can discuss it from there.

**Comment by pataquets** [comment]
Hi @isamert.
Wouldn't it be better to keep this issue open to allow potential interested users/contributors to discover it? It would improve the odds of moving forward.
However, I'm well aware and understand maintainer's preferences on keeping the issue list tidy. In case it's your preference, how about labeling as "help wanted"/"pr accepted" to let everybody know it's an acceptable feature to work on? This includes myself, of course at some point in the future (closed issues are hidden in users' issue list).
In any case, thanks for considering.

**Comment by isamert** [comment]
Your point makes sense but I would like to keep the issues I'm going
to work on or the ones already haven an assignee. Otherwise it becomes
confusing. And the word "issues" has kind of a negative connotation on
it where a project with lot's of open issues may be perceived as
unstable/unusable. I know it's not the case but it's a matter of
perception.

I took a note of this, and I will reconsider my workflow to maybe
filter out some of the labels from my personal backlog or just simply
assigning myself to the issue.

I guess it's not going to be very helpful to tag a closed issue as
you've said but I will tag it for now and maybe I'll reopen it once I
decide on a new workflow.

Thanks for being interested! If you have further ideas feel free to
share.
