### ISSUE TITLE
Lab can not get any Git config on Windows

### ISSUE THREAD

**Issue by sebastiaanspeck** [isamert/lab.el#8]
When using lab.el out-of-the-box on Windows, everything it tries to read from my `.gitconfig`, results in the message: `"error: invalid key: 'remote.origin.url'"`. When I debugged the code, it seemed that I had to remove the `'` around `%s` before getting lab.el to work on Windows. On MacOS it works with `'` and without `'` around `%s`.

```elisp

(defun lab-git-get-config (conf)
  "`git config --get CONF' wrapper."
  (thread-last
    (format "git config --get '%s'" conf)
    shell-command-to-string
    s-trim))
```

**Comment by isamert** [comment]
Thanks a lot for the debugging and fixing!
